drop extension if exists "pg_net";

-- Create type only if it doesn't exist
DO $$ BEGIN
  CREATE TYPE "public"."publication_status" AS ENUM ('draft', 'published');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;


  create table if not exists "public"."group" (
    "id" uuid not null default gen_random_uuid(),
    "leader_id" uuid not null,
    "community" smallint not null
      );


alter table "public"."group" enable row level security;


  create table if not exists "public"."group_meeting" (
    "id" uuid not null,
    "group_id" uuid not null,
    "meeting_date" date not null,
    "notes" text,
    "created_by" uuid not null,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now()
      );



  create table if not exists "public"."group_meeting_record" (
    "group_meeting_id" uuid not null,
    "member_id" uuid not null,
    "group_attended" boolean not null,
    "worship_attended" boolean not null,
    "prayer_request" text,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now()
      );



  create table if not exists "public"."group_member" (
    "group_id" uuid not null,
    "member_id" uuid not null
      );


alter table "public"."group_member" enable row level security;


  create table if not exists "public"."internal_team_application" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "email" text not null,
    "phone" text not null,
    "interest" text not null,
    "confirmation" boolean not null,
    "tithe" boolean not null
      );


alter table "public"."internal_team_application" enable row level security;


  create table if not exists "public"."member" (
    "created_at" timestamp without time zone not null default (now() AT TIME ZONE 'utc'::text),
    "name_in_korean" text,
    "name" text,
    "sex" smallint,
    "dob" date,
    "phone_number" text,
    "email" text,
    "address" text,
    "is_baptized" boolean,
    "is_confirmed" boolean,
    "status" text,
    "church_id" integer,
    "id" uuid not null default gen_random_uuid(),
    "updated_at" timestamp without time zone
      );


alter table "public"."member" enable row level security;


  create table if not exists "public"."permission" (
    "id" bigint generated by default as identity not null,
    "slug" text not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
      );


alter table "public"."permission" enable row level security;


  create table if not exists "public"."role" (
    "id" bigint generated by default as identity not null,
    "description" text not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
      );


alter table "public"."role" enable row level security;


  create table if not exists "public"."role_permission" (
    "id" bigint generated by default as identity not null,
    "role_id" bigint not null,
    "permission_id" bigint not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
      );



  create table if not exists "public"."test_table_to_test_for_api" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "text_column" text,
    "phone_number" text,
    "name" text
      );


alter table "public"."test_table_to_test_for_api" enable row level security;


  create table if not exists "public"."user" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "google_id" numeric not null,
    "email" text not null,
    "given_name" text not null,
    "family_name" text not null,
    "name" text not null,
    "image_url" text
      );


alter table "public"."user" enable row level security;


  create table if not exists "public"."user_role" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "role_id" bigint not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
      );


alter table "public"."user_role" enable row level security;

-- Add IF NOT EXISTS to all index creations
CREATE UNIQUE INDEX IF NOT EXISTS group_meeting_pkey ON public.group_meeting USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS group_meeting_record_pkey ON public.group_meeting_record USING btree (group_meeting_id, member_id);

CREATE UNIQUE INDEX IF NOT EXISTS group_member_pkey ON public.group_member USING btree (group_id, member_id);

CREATE UNIQUE INDEX IF NOT EXISTS group_pkey ON public."group" USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS internal_team_application_pkey ON public.internal_team_application USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS member_pkey ON public.member USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS member_uid_key ON public.member USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS permission_pkey ON public.permission USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS role_permission_pkey ON public.role_permission USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS role_pkey ON public.role USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS test_table_to_test_for_api_pkey ON public.test_table_to_test_for_api USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS unique_group_meeting_date ON public.group_meeting USING btree (group_id, meeting_date);

CREATE UNIQUE INDEX IF NOT EXISTS user_google_id_key ON public."user" USING btree (google_id);

CREATE UNIQUE INDEX IF NOT EXISTS user_pkey ON public."user" USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS user_role_pkey ON public.user_role USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS user_role_user_id_key ON public.user_role USING btree (user_id);

-- Wrap all constraint additions in DO blocks to check if they exist
-- This makes them idempotent (safe to run multiple times)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'group_pkey') THEN
    ALTER TABLE "public"."group" ADD CONSTRAINT "group_pkey" PRIMARY KEY USING INDEX "group_pkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'group_meeting_pkey') THEN
    ALTER TABLE "public"."group_meeting" ADD CONSTRAINT "group_meeting_pkey" PRIMARY KEY USING INDEX "group_meeting_pkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'group_meeting_record_pkey') THEN
    ALTER TABLE "public"."group_meeting_record" ADD CONSTRAINT "group_meeting_record_pkey" PRIMARY KEY USING INDEX "group_meeting_record_pkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'group_member_pkey') THEN
    ALTER TABLE "public"."group_member" ADD CONSTRAINT "group_member_pkey" PRIMARY KEY USING INDEX "group_member_pkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'internal_team_application_pkey') THEN
    ALTER TABLE "public"."internal_team_application" ADD CONSTRAINT "internal_team_application_pkey" PRIMARY KEY USING INDEX "internal_team_application_pkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'member_pkey') THEN
    ALTER TABLE "public"."member" ADD CONSTRAINT "member_pkey" PRIMARY KEY USING INDEX "member_pkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'permission_pkey') THEN
    ALTER TABLE "public"."permission" ADD CONSTRAINT "permission_pkey" PRIMARY KEY USING INDEX "permission_pkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'role_pkey') THEN
    ALTER TABLE "public"."role" ADD CONSTRAINT "role_pkey" PRIMARY KEY USING INDEX "role_pkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'role_permission_pkey') THEN
    ALTER TABLE "public"."role_permission" ADD CONSTRAINT "role_permission_pkey" PRIMARY KEY USING INDEX "role_permission_pkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'test_table_to_test_for_api_pkey') THEN
    ALTER TABLE "public"."test_table_to_test_for_api" ADD CONSTRAINT "test_table_to_test_for_api_pkey" PRIMARY KEY USING INDEX "test_table_to_test_for_api_pkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_pkey') THEN
    ALTER TABLE "public"."user" ADD CONSTRAINT "user_pkey" PRIMARY KEY USING INDEX "user_pkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_role_pkey') THEN
    ALTER TABLE "public"."user_role" ADD CONSTRAINT "user_role_pkey" PRIMARY KEY USING INDEX "user_role_pkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'group_leader_id_fkey') THEN
    ALTER TABLE "public"."group" ADD CONSTRAINT "group_leader_id_fkey" FOREIGN KEY (leader_id) REFERENCES public.member(id) ON UPDATE CASCADE NOT VALID;
    ALTER TABLE "public"."group" VALIDATE CONSTRAINT "group_leader_id_fkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_group_meeting_date') THEN
    ALTER TABLE "public"."group_meeting" ADD CONSTRAINT "unique_group_meeting_date" UNIQUE USING INDEX "unique_group_meeting_date";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'group_member_group_id_fkey') THEN
    ALTER TABLE "public"."group_member" ADD CONSTRAINT "group_member_group_id_fkey" FOREIGN KEY (group_id) REFERENCES public."group"(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
    ALTER TABLE "public"."group_member" VALIDATE CONSTRAINT "group_member_group_id_fkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'group_member_member_id_fkey') THEN
    ALTER TABLE "public"."group_member" ADD CONSTRAINT "group_member_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.member(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
    ALTER TABLE "public"."group_member" VALIDATE CONSTRAINT "group_member_member_id_fkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'member_uid_key') THEN
    ALTER TABLE "public"."member" ADD CONSTRAINT "member_uid_key" UNIQUE USING INDEX "member_uid_key";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'role_permission_permission_id_fkey') THEN
    ALTER TABLE "public"."role_permission" ADD CONSTRAINT "role_permission_permission_id_fkey" FOREIGN KEY (permission_id) REFERENCES public.permission(id) ON DELETE CASCADE NOT VALID;
    ALTER TABLE "public"."role_permission" VALIDATE CONSTRAINT "role_permission_permission_id_fkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'role_permission_role_id_fkey') THEN
    ALTER TABLE "public"."role_permission" ADD CONSTRAINT "role_permission_role_id_fkey" FOREIGN KEY (role_id) REFERENCES public.role(id) ON DELETE CASCADE NOT VALID;
    ALTER TABLE "public"."role_permission" VALIDATE CONSTRAINT "role_permission_role_id_fkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_google_id_key') THEN
    ALTER TABLE "public"."user" ADD CONSTRAINT "user_google_id_key" UNIQUE USING INDEX "user_google_id_key";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_role_role_id_fkey') THEN
    ALTER TABLE "public"."user_role" ADD CONSTRAINT "user_role_role_id_fkey" FOREIGN KEY (role_id) REFERENCES public.role(id) ON DELETE CASCADE NOT VALID;
    ALTER TABLE "public"."user_role" VALIDATE CONSTRAINT "user_role_role_id_fkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_role_user_id_fkey') THEN
    ALTER TABLE "public"."user_role" ADD CONSTRAINT "user_role_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE NOT VALID;
    ALTER TABLE "public"."user_role" VALIDATE CONSTRAINT "user_role_user_id_fkey";
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_role_user_id_key') THEN
    ALTER TABLE "public"."user_role" ADD CONSTRAINT "user_role_user_id_key" UNIQUE USING INDEX "user_role_user_id_key";
  END IF;
END $$;

set check_function_bodies = off;

create or replace view "public"."members_upcoming_birthdays_view" as  SELECT created_at,
    name_in_korean,
    name,
    sex,
    dob,
    phone_number,
    email,
    address,
    is_baptized,
    is_confirmed,
    status,
    church_id,
    id,
    updated_at,
    date_trunc('day'::text, (dob + (((EXTRACT(year FROM now()) - EXTRACT(year FROM dob)))::double precision * '1 year'::interval))) AS this_year_birthday
   FROM public.member;


CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
NEW.updated_at = NOW();
RETURN NEW;
END;
$function$
;

grant delete on table "public"."group" to "anon";

grant insert on table "public"."group" to "anon";

grant references on table "public"."group" to "anon";

grant select on table "public"."group" to "anon";

grant trigger on table "public"."group" to "anon";

grant truncate on table "public"."group" to "anon";

grant update on table "public"."group" to "anon";

grant delete on table "public"."group" to "authenticated";

grant insert on table "public"."group" to "authenticated";

grant references on table "public"."group" to "authenticated";

grant select on table "public"."group" to "authenticated";

grant trigger on table "public"."group" to "authenticated";

grant truncate on table "public"."group" to "authenticated";

grant update on table "public"."group" to "authenticated";

grant delete on table "public"."group" to "service_role";

grant insert on table "public"."group" to "service_role";

grant references on table "public"."group" to "service_role";

grant select on table "public"."group" to "service_role";

grant trigger on table "public"."group" to "service_role";

grant truncate on table "public"."group" to "service_role";

grant update on table "public"."group" to "service_role";

grant delete on table "public"."group_meeting" to "anon";

grant insert on table "public"."group_meeting" to "anon";

grant references on table "public"."group_meeting" to "anon";

grant select on table "public"."group_meeting" to "anon";

grant trigger on table "public"."group_meeting" to "anon";

grant truncate on table "public"."group_meeting" to "anon";

grant update on table "public"."group_meeting" to "anon";

grant delete on table "public"."group_meeting" to "authenticated";

grant insert on table "public"."group_meeting" to "authenticated";

grant references on table "public"."group_meeting" to "authenticated";

grant select on table "public"."group_meeting" to "authenticated";

grant trigger on table "public"."group_meeting" to "authenticated";

grant truncate on table "public"."group_meeting" to "authenticated";

grant update on table "public"."group_meeting" to "authenticated";

grant delete on table "public"."group_meeting" to "service_role";

grant insert on table "public"."group_meeting" to "service_role";

grant references on table "public"."group_meeting" to "service_role";

grant select on table "public"."group_meeting" to "service_role";

grant trigger on table "public"."group_meeting" to "service_role";

grant truncate on table "public"."group_meeting" to "service_role";

grant update on table "public"."group_meeting" to "service_role";

grant delete on table "public"."group_meeting_record" to "anon";

grant insert on table "public"."group_meeting_record" to "anon";

grant references on table "public"."group_meeting_record" to "anon";

grant select on table "public"."group_meeting_record" to "anon";

grant trigger on table "public"."group_meeting_record" to "anon";

grant truncate on table "public"."group_meeting_record" to "anon";

grant update on table "public"."group_meeting_record" to "anon";

grant delete on table "public"."group_meeting_record" to "authenticated";

grant insert on table "public"."group_meeting_record" to "authenticated";

grant references on table "public"."group_meeting_record" to "authenticated";

grant select on table "public"."group_meeting_record" to "authenticated";

grant trigger on table "public"."group_meeting_record" to "authenticated";

grant truncate on table "public"."group_meeting_record" to "authenticated";

grant update on table "public"."group_meeting_record" to "authenticated";

grant delete on table "public"."group_meeting_record" to "service_role";

grant insert on table "public"."group_meeting_record" to "service_role";

grant references on table "public"."group_meeting_record" to "service_role";

grant select on table "public"."group_meeting_record" to "service_role";

grant trigger on table "public"."group_meeting_record" to "service_role";

grant truncate on table "public"."group_meeting_record" to "service_role";

grant update on table "public"."group_meeting_record" to "service_role";

grant delete on table "public"."group_member" to "anon";

grant insert on table "public"."group_member" to "anon";

grant references on table "public"."group_member" to "anon";

grant select on table "public"."group_member" to "anon";

grant trigger on table "public"."group_member" to "anon";

grant truncate on table "public"."group_member" to "anon";

grant update on table "public"."group_member" to "anon";

grant delete on table "public"."group_member" to "authenticated";

grant insert on table "public"."group_member" to "authenticated";

grant references on table "public"."group_member" to "authenticated";

grant select on table "public"."group_member" to "authenticated";

grant trigger on table "public"."group_member" to "authenticated";

grant truncate on table "public"."group_member" to "authenticated";

grant update on table "public"."group_member" to "authenticated";

grant delete on table "public"."group_member" to "service_role";

grant insert on table "public"."group_member" to "service_role";

grant references on table "public"."group_member" to "service_role";

grant select on table "public"."group_member" to "service_role";

grant trigger on table "public"."group_member" to "service_role";

grant truncate on table "public"."group_member" to "service_role";

grant update on table "public"."group_member" to "service_role";

grant delete on table "public"."internal_team_application" to "anon";

grant insert on table "public"."internal_team_application" to "anon";

grant references on table "public"."internal_team_application" to "anon";

grant select on table "public"."internal_team_application" to "anon";

grant trigger on table "public"."internal_team_application" to "anon";

grant truncate on table "public"."internal_team_application" to "anon";

grant update on table "public"."internal_team_application" to "anon";

grant delete on table "public"."internal_team_application" to "authenticated";

grant insert on table "public"."internal_team_application" to "authenticated";

grant references on table "public"."internal_team_application" to "authenticated";

grant select on table "public"."internal_team_application" to "authenticated";

grant trigger on table "public"."internal_team_application" to "authenticated";

grant truncate on table "public"."internal_team_application" to "authenticated";

grant update on table "public"."internal_team_application" to "authenticated";

grant delete on table "public"."internal_team_application" to "service_role";

grant insert on table "public"."internal_team_application" to "service_role";

grant references on table "public"."internal_team_application" to "service_role";

grant select on table "public"."internal_team_application" to "service_role";

grant trigger on table "public"."internal_team_application" to "service_role";

grant truncate on table "public"."internal_team_application" to "service_role";

grant update on table "public"."internal_team_application" to "service_role";

grant delete on table "public"."member" to "anon";

grant insert on table "public"."member" to "anon";

grant references on table "public"."member" to "anon";

grant select on table "public"."member" to "anon";

grant trigger on table "public"."member" to "anon";

grant truncate on table "public"."member" to "anon";

grant update on table "public"."member" to "anon";

grant delete on table "public"."member" to "authenticated";

grant insert on table "public"."member" to "authenticated";

grant references on table "public"."member" to "authenticated";

grant select on table "public"."member" to "authenticated";

grant trigger on table "public"."member" to "authenticated";

grant truncate on table "public"."member" to "authenticated";

grant update on table "public"."member" to "authenticated";

grant delete on table "public"."member" to "service_role";

grant insert on table "public"."member" to "service_role";

grant references on table "public"."member" to "service_role";

grant select on table "public"."member" to "service_role";

grant trigger on table "public"."member" to "service_role";

grant truncate on table "public"."member" to "service_role";

grant update on table "public"."member" to "service_role";

grant delete on table "public"."permission" to "anon";

grant insert on table "public"."permission" to "anon";

grant references on table "public"."permission" to "anon";

grant select on table "public"."permission" to "anon";

grant trigger on table "public"."permission" to "anon";

grant truncate on table "public"."permission" to "anon";

grant update on table "public"."permission" to "anon";

grant delete on table "public"."permission" to "authenticated";

grant insert on table "public"."permission" to "authenticated";

grant references on table "public"."permission" to "authenticated";

grant select on table "public"."permission" to "authenticated";

grant trigger on table "public"."permission" to "authenticated";

grant truncate on table "public"."permission" to "authenticated";

grant update on table "public"."permission" to "authenticated";

grant delete on table "public"."permission" to "service_role";

grant insert on table "public"."permission" to "service_role";

grant references on table "public"."permission" to "service_role";

grant select on table "public"."permission" to "service_role";

grant trigger on table "public"."permission" to "service_role";

grant truncate on table "public"."permission" to "service_role";

grant update on table "public"."permission" to "service_role";

grant delete on table "public"."role" to "anon";

grant insert on table "public"."role" to "anon";

grant references on table "public"."role" to "anon";

grant select on table "public"."role" to "anon";

grant trigger on table "public"."role" to "anon";

grant truncate on table "public"."role" to "anon";

grant update on table "public"."role" to "anon";

grant delete on table "public"."role" to "authenticated";

grant insert on table "public"."role" to "authenticated";

grant references on table "public"."role" to "authenticated";

grant select on table "public"."role" to "authenticated";

grant trigger on table "public"."role" to "authenticated";

grant truncate on table "public"."role" to "authenticated";

grant update on table "public"."role" to "authenticated";

grant delete on table "public"."role" to "service_role";

grant insert on table "public"."role" to "service_role";

grant references on table "public"."role" to "service_role";

grant select on table "public"."role" to "service_role";

grant trigger on table "public"."role" to "service_role";

grant truncate on table "public"."role" to "service_role";

grant update on table "public"."role" to "service_role";

grant delete on table "public"."role_permission" to "anon";

grant insert on table "public"."role_permission" to "anon";

grant references on table "public"."role_permission" to "anon";

grant select on table "public"."role_permission" to "anon";

grant trigger on table "public"."role_permission" to "anon";

grant truncate on table "public"."role_permission" to "anon";

grant update on table "public"."role_permission" to "anon";

grant delete on table "public"."role_permission" to "authenticated";

grant insert on table "public"."role_permission" to "authenticated";

grant references on table "public"."role_permission" to "authenticated";

grant select on table "public"."role_permission" to "authenticated";

grant trigger on table "public"."role_permission" to "authenticated";

grant truncate on table "public"."role_permission" to "authenticated";

grant update on table "public"."role_permission" to "authenticated";

grant delete on table "public"."role_permission" to "service_role";

grant insert on table "public"."role_permission" to "service_role";

grant references on table "public"."role_permission" to "service_role";

grant select on table "public"."role_permission" to "service_role";

grant trigger on table "public"."role_permission" to "service_role";

grant truncate on table "public"."role_permission" to "service_role";

grant update on table "public"."role_permission" to "service_role";

grant delete on table "public"."test_table_to_test_for_api" to "anon";

grant insert on table "public"."test_table_to_test_for_api" to "anon";

grant references on table "public"."test_table_to_test_for_api" to "anon";

grant select on table "public"."test_table_to_test_for_api" to "anon";

grant trigger on table "public"."test_table_to_test_for_api" to "anon";

grant truncate on table "public"."test_table_to_test_for_api" to "anon";

grant update on table "public"."test_table_to_test_for_api" to "anon";

grant delete on table "public"."test_table_to_test_for_api" to "authenticated";

grant insert on table "public"."test_table_to_test_for_api" to "authenticated";

grant references on table "public"."test_table_to_test_for_api" to "authenticated";

grant select on table "public"."test_table_to_test_for_api" to "authenticated";

grant trigger on table "public"."test_table_to_test_for_api" to "authenticated";

grant truncate on table "public"."test_table_to_test_for_api" to "authenticated";

grant update on table "public"."test_table_to_test_for_api" to "authenticated";

grant delete on table "public"."test_table_to_test_for_api" to "service_role";

grant insert on table "public"."test_table_to_test_for_api" to "service_role";

grant references on table "public"."test_table_to_test_for_api" to "service_role";

grant select on table "public"."test_table_to_test_for_api" to "service_role";

grant trigger on table "public"."test_table_to_test_for_api" to "service_role";

grant truncate on table "public"."test_table_to_test_for_api" to "service_role";

grant update on table "public"."test_table_to_test_for_api" to "service_role";

grant delete on table "public"."user" to "anon";

grant insert on table "public"."user" to "anon";

grant references on table "public"."user" to "anon";

grant select on table "public"."user" to "anon";

grant trigger on table "public"."user" to "anon";

grant truncate on table "public"."user" to "anon";

grant update on table "public"."user" to "anon";

grant delete on table "public"."user" to "authenticated";

grant insert on table "public"."user" to "authenticated";

grant references on table "public"."user" to "authenticated";

grant select on table "public"."user" to "authenticated";

grant trigger on table "public"."user" to "authenticated";

grant truncate on table "public"."user" to "authenticated";

grant update on table "public"."user" to "authenticated";

grant delete on table "public"."user" to "service_role";

grant insert on table "public"."user" to "service_role";

grant references on table "public"."user" to "service_role";

grant select on table "public"."user" to "service_role";

grant trigger on table "public"."user" to "service_role";

grant truncate on table "public"."user" to "service_role";

grant update on table "public"."user" to "service_role";

grant delete on table "public"."user_role" to "anon";

grant insert on table "public"."user_role" to "anon";

grant references on table "public"."user_role" to "anon";

grant select on table "public"."user_role" to "anon";

grant trigger on table "public"."user_role" to "anon";

grant truncate on table "public"."user_role" to "anon";

grant update on table "public"."user_role" to "anon";

grant delete on table "public"."user_role" to "authenticated";

grant insert on table "public"."user_role" to "authenticated";

grant references on table "public"."user_role" to "authenticated";

grant select on table "public"."user_role" to "authenticated";

grant trigger on table "public"."user_role" to "authenticated";

grant truncate on table "public"."user_role" to "authenticated";

grant update on table "public"."user_role" to "authenticated";

grant delete on table "public"."user_role" to "service_role";

grant insert on table "public"."user_role" to "service_role";

grant references on table "public"."user_role" to "service_role";

grant select on table "public"."user_role" to "service_role";

grant trigger on table "public"."user_role" to "service_role";

grant truncate on table "public"."user_role" to "service_role";

grant update on table "public"."user_role" to "service_role";

-- Drop triggers if they exist before creating them
DROP TRIGGER IF EXISTS update_group_meeting_updated_at ON public.group_meeting;
CREATE TRIGGER update_group_meeting_updated_at BEFORE UPDATE ON public.group_meeting FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_group_meeting_record_updated_at ON public.group_meeting_record;
CREATE TRIGGER update_group_meeting_record_updated_at BEFORE UPDATE ON public.group_meeting_record FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


