drop extension if exists "pg_net";

create type "public"."publication_status" as enum ('draft', 'published');


  create table "public"."group" (
    "id" uuid not null default gen_random_uuid(),
    "leader_id" uuid not null,
    "community" smallint not null
      );


alter table "public"."group" enable row level security;


  create table "public"."group_meeting" (
    "id" uuid not null,
    "group_id" uuid not null,
    "meeting_date" date not null,
    "notes" text,
    "created_by" uuid not null,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now()
      );



  create table "public"."group_meeting_record" (
    "group_meeting_id" uuid not null,
    "member_id" uuid not null,
    "group_attended" boolean not null,
    "worship_attended" boolean not null,
    "prayer_request" text,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now()
      );



  create table "public"."group_member" (
    "group_id" uuid not null,
    "member_id" uuid not null
      );


alter table "public"."group_member" enable row level security;


  create table "public"."internal_team_application" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "email" text not null,
    "phone" text not null,
    "interest" text not null,
    "confirmation" boolean not null,
    "tithe" boolean not null
      );


alter table "public"."internal_team_application" enable row level security;


  create table "public"."member" (
    "created_at" timestamp without time zone not null default (now() AT TIME ZONE 'utc'::text),
    "name_in_korean" text,
    "name" text,
    "sex" smallint,
    "dob" date,
    "phone_number" text,
    "email" text,
    "address" text,
    "is_baptized" boolean,
    "is_confirmed" boolean,
    "status" text,
    "church_id" integer,
    "id" uuid not null default gen_random_uuid(),
    "updated_at" timestamp without time zone
      );


alter table "public"."member" enable row level security;


  create table "public"."permission" (
    "id" bigint generated by default as identity not null,
    "slug" text not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
      );


alter table "public"."permission" enable row level security;


  create table "public"."role" (
    "id" bigint generated by default as identity not null,
    "description" text not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
      );


alter table "public"."role" enable row level security;


  create table "public"."role_permission" (
    "id" bigint generated by default as identity not null,
    "role_id" bigint not null,
    "permission_id" bigint not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
      );



  create table "public"."test_table_to_test_for_api" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "text_column" text,
    "phone_number" text,
    "name" text
      );


alter table "public"."test_table_to_test_for_api" enable row level security;


  create table "public"."user" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "google_id" numeric not null,
    "email" text not null,
    "given_name" text not null,
    "family_name" text not null,
    "name" text not null,
    "image_url" text
      );


alter table "public"."user" enable row level security;


  create table "public"."user_role" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "role_id" bigint not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
      );


alter table "public"."user_role" enable row level security;

CREATE UNIQUE INDEX group_meeting_pkey ON public.group_meeting USING btree (id);

CREATE UNIQUE INDEX group_meeting_record_pkey ON public.group_meeting_record USING btree (group_meeting_id, member_id);

CREATE UNIQUE INDEX group_member_pkey ON public.group_member USING btree (group_id, member_id);

CREATE UNIQUE INDEX group_pkey ON public."group" USING btree (id);

CREATE UNIQUE INDEX internal_team_application_pkey ON public.internal_team_application USING btree (id);

CREATE UNIQUE INDEX member_pkey ON public.member USING btree (id);

CREATE UNIQUE INDEX member_uid_key ON public.member USING btree (id);

CREATE UNIQUE INDEX permission_pkey ON public.permission USING btree (id);

CREATE UNIQUE INDEX role_permission_pkey ON public.role_permission USING btree (id);

CREATE UNIQUE INDEX role_pkey ON public.role USING btree (id);

CREATE UNIQUE INDEX test_table_to_test_for_api_pkey ON public.test_table_to_test_for_api USING btree (id);

CREATE UNIQUE INDEX unique_group_meeting_date ON public.group_meeting USING btree (group_id, meeting_date);

CREATE UNIQUE INDEX user_google_id_key ON public."user" USING btree (google_id);

CREATE UNIQUE INDEX user_pkey ON public."user" USING btree (id);

CREATE UNIQUE INDEX user_role_pkey ON public.user_role USING btree (id);

CREATE UNIQUE INDEX user_role_user_id_key ON public.user_role USING btree (user_id);

alter table "public"."group" add constraint "group_pkey" PRIMARY KEY using index "group_pkey";

alter table "public"."group_meeting" add constraint "group_meeting_pkey" PRIMARY KEY using index "group_meeting_pkey";

alter table "public"."group_meeting_record" add constraint "group_meeting_record_pkey" PRIMARY KEY using index "group_meeting_record_pkey";

alter table "public"."group_member" add constraint "group_member_pkey" PRIMARY KEY using index "group_member_pkey";

alter table "public"."internal_team_application" add constraint "internal_team_application_pkey" PRIMARY KEY using index "internal_team_application_pkey";

alter table "public"."member" add constraint "member_pkey" PRIMARY KEY using index "member_pkey";

alter table "public"."permission" add constraint "permission_pkey" PRIMARY KEY using index "permission_pkey";

alter table "public"."role" add constraint "role_pkey" PRIMARY KEY using index "role_pkey";

alter table "public"."role_permission" add constraint "role_permission_pkey" PRIMARY KEY using index "role_permission_pkey";

alter table "public"."test_table_to_test_for_api" add constraint "test_table_to_test_for_api_pkey" PRIMARY KEY using index "test_table_to_test_for_api_pkey";

alter table "public"."user" add constraint "user_pkey" PRIMARY KEY using index "user_pkey";

alter table "public"."user_role" add constraint "user_role_pkey" PRIMARY KEY using index "user_role_pkey";

alter table "public"."group" add constraint "group_leader_id_fkey" FOREIGN KEY (leader_id) REFERENCES public.member(id) ON UPDATE CASCADE not valid;

alter table "public"."group" validate constraint "group_leader_id_fkey";

alter table "public"."group_meeting" add constraint "unique_group_meeting_date" UNIQUE using index "unique_group_meeting_date";

alter table "public"."group_member" add constraint "group_member_group_id_fkey" FOREIGN KEY (group_id) REFERENCES public."group"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."group_member" validate constraint "group_member_group_id_fkey";

alter table "public"."group_member" add constraint "group_member_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.member(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."group_member" validate constraint "group_member_member_id_fkey";

alter table "public"."member" add constraint "member_uid_key" UNIQUE using index "member_uid_key";

alter table "public"."role_permission" add constraint "role_permission_permission_id_fkey" FOREIGN KEY (permission_id) REFERENCES public.permission(id) ON DELETE CASCADE not valid;

alter table "public"."role_permission" validate constraint "role_permission_permission_id_fkey";

alter table "public"."role_permission" add constraint "role_permission_role_id_fkey" FOREIGN KEY (role_id) REFERENCES public.role(id) ON DELETE CASCADE not valid;

alter table "public"."role_permission" validate constraint "role_permission_role_id_fkey";

alter table "public"."user" add constraint "user_google_id_key" UNIQUE using index "user_google_id_key";

alter table "public"."user_role" add constraint "user_role_role_id_fkey" FOREIGN KEY (role_id) REFERENCES public.role(id) ON DELETE CASCADE not valid;

alter table "public"."user_role" validate constraint "user_role_role_id_fkey";

alter table "public"."user_role" add constraint "user_role_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE not valid;

alter table "public"."user_role" validate constraint "user_role_user_id_fkey";

alter table "public"."user_role" add constraint "user_role_user_id_key" UNIQUE using index "user_role_user_id_key";

set check_function_bodies = off;

create or replace view "public"."members_upcoming_birthdays_view" as  SELECT created_at,
    name_in_korean,
    name,
    sex,
    dob,
    phone_number,
    email,
    address,
    is_baptized,
    is_confirmed,
    status,
    church_id,
    id,
    updated_at,
    date_trunc('day'::text, (dob + (((EXTRACT(year FROM now()) - EXTRACT(year FROM dob)))::double precision * '1 year'::interval))) AS this_year_birthday
   FROM public.member;


CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
NEW.updated_at = NOW();
RETURN NEW;
END;
$function$
;

grant delete on table "public"."group" to "anon";

grant insert on table "public"."group" to "anon";

grant references on table "public"."group" to "anon";

grant select on table "public"."group" to "anon";

grant trigger on table "public"."group" to "anon";

grant truncate on table "public"."group" to "anon";

grant update on table "public"."group" to "anon";

grant delete on table "public"."group" to "authenticated";

grant insert on table "public"."group" to "authenticated";

grant references on table "public"."group" to "authenticated";

grant select on table "public"."group" to "authenticated";

grant trigger on table "public"."group" to "authenticated";

grant truncate on table "public"."group" to "authenticated";

grant update on table "public"."group" to "authenticated";

grant delete on table "public"."group" to "service_role";

grant insert on table "public"."group" to "service_role";

grant references on table "public"."group" to "service_role";

grant select on table "public"."group" to "service_role";

grant trigger on table "public"."group" to "service_role";

grant truncate on table "public"."group" to "service_role";

grant update on table "public"."group" to "service_role";

grant delete on table "public"."group_meeting" to "anon";

grant insert on table "public"."group_meeting" to "anon";

grant references on table "public"."group_meeting" to "anon";

grant select on table "public"."group_meeting" to "anon";

grant trigger on table "public"."group_meeting" to "anon";

grant truncate on table "public"."group_meeting" to "anon";

grant update on table "public"."group_meeting" to "anon";

grant delete on table "public"."group_meeting" to "authenticated";

grant insert on table "public"."group_meeting" to "authenticated";

grant references on table "public"."group_meeting" to "authenticated";

grant select on table "public"."group_meeting" to "authenticated";

grant trigger on table "public"."group_meeting" to "authenticated";

grant truncate on table "public"."group_meeting" to "authenticated";

grant update on table "public"."group_meeting" to "authenticated";

grant delete on table "public"."group_meeting" to "service_role";

grant insert on table "public"."group_meeting" to "service_role";

grant references on table "public"."group_meeting" to "service_role";

grant select on table "public"."group_meeting" to "service_role";

grant trigger on table "public"."group_meeting" to "service_role";

grant truncate on table "public"."group_meeting" to "service_role";

grant update on table "public"."group_meeting" to "service_role";

grant delete on table "public"."group_meeting_record" to "anon";

grant insert on table "public"."group_meeting_record" to "anon";

grant references on table "public"."group_meeting_record" to "anon";

grant select on table "public"."group_meeting_record" to "anon";

grant trigger on table "public"."group_meeting_record" to "anon";

grant truncate on table "public"."group_meeting_record" to "anon";

grant update on table "public"."group_meeting_record" to "anon";

grant delete on table "public"."group_meeting_record" to "authenticated";

grant insert on table "public"."group_meeting_record" to "authenticated";

grant references on table "public"."group_meeting_record" to "authenticated";

grant select on table "public"."group_meeting_record" to "authenticated";

grant trigger on table "public"."group_meeting_record" to "authenticated";

grant truncate on table "public"."group_meeting_record" to "authenticated";

grant update on table "public"."group_meeting_record" to "authenticated";

grant delete on table "public"."group_meeting_record" to "service_role";

grant insert on table "public"."group_meeting_record" to "service_role";

grant references on table "public"."group_meeting_record" to "service_role";

grant select on table "public"."group_meeting_record" to "service_role";

grant trigger on table "public"."group_meeting_record" to "service_role";

grant truncate on table "public"."group_meeting_record" to "service_role";

grant update on table "public"."group_meeting_record" to "service_role";

grant delete on table "public"."group_member" to "anon";

grant insert on table "public"."group_member" to "anon";

grant references on table "public"."group_member" to "anon";

grant select on table "public"."group_member" to "anon";

grant trigger on table "public"."group_member" to "anon";

grant truncate on table "public"."group_member" to "anon";

grant update on table "public"."group_member" to "anon";

grant delete on table "public"."group_member" to "authenticated";

grant insert on table "public"."group_member" to "authenticated";

grant references on table "public"."group_member" to "authenticated";

grant select on table "public"."group_member" to "authenticated";

grant trigger on table "public"."group_member" to "authenticated";

grant truncate on table "public"."group_member" to "authenticated";

grant update on table "public"."group_member" to "authenticated";

grant delete on table "public"."group_member" to "service_role";

grant insert on table "public"."group_member" to "service_role";

grant references on table "public"."group_member" to "service_role";

grant select on table "public"."group_member" to "service_role";

grant trigger on table "public"."group_member" to "service_role";

grant truncate on table "public"."group_member" to "service_role";

grant update on table "public"."group_member" to "service_role";

grant delete on table "public"."internal_team_application" to "anon";

grant insert on table "public"."internal_team_application" to "anon";

grant references on table "public"."internal_team_application" to "anon";

grant select on table "public"."internal_team_application" to "anon";

grant trigger on table "public"."internal_team_application" to "anon";

grant truncate on table "public"."internal_team_application" to "anon";

grant update on table "public"."internal_team_application" to "anon";

grant delete on table "public"."internal_team_application" to "authenticated";

grant insert on table "public"."internal_team_application" to "authenticated";

grant references on table "public"."internal_team_application" to "authenticated";

grant select on table "public"."internal_team_application" to "authenticated";

grant trigger on table "public"."internal_team_application" to "authenticated";

grant truncate on table "public"."internal_team_application" to "authenticated";

grant update on table "public"."internal_team_application" to "authenticated";

grant delete on table "public"."internal_team_application" to "service_role";

grant insert on table "public"."internal_team_application" to "service_role";

grant references on table "public"."internal_team_application" to "service_role";

grant select on table "public"."internal_team_application" to "service_role";

grant trigger on table "public"."internal_team_application" to "service_role";

grant truncate on table "public"."internal_team_application" to "service_role";

grant update on table "public"."internal_team_application" to "service_role";

grant delete on table "public"."member" to "anon";

grant insert on table "public"."member" to "anon";

grant references on table "public"."member" to "anon";

grant select on table "public"."member" to "anon";

grant trigger on table "public"."member" to "anon";

grant truncate on table "public"."member" to "anon";

grant update on table "public"."member" to "anon";

grant delete on table "public"."member" to "authenticated";

grant insert on table "public"."member" to "authenticated";

grant references on table "public"."member" to "authenticated";

grant select on table "public"."member" to "authenticated";

grant trigger on table "public"."member" to "authenticated";

grant truncate on table "public"."member" to "authenticated";

grant update on table "public"."member" to "authenticated";

grant delete on table "public"."member" to "service_role";

grant insert on table "public"."member" to "service_role";

grant references on table "public"."member" to "service_role";

grant select on table "public"."member" to "service_role";

grant trigger on table "public"."member" to "service_role";

grant truncate on table "public"."member" to "service_role";

grant update on table "public"."member" to "service_role";

grant delete on table "public"."permission" to "anon";

grant insert on table "public"."permission" to "anon";

grant references on table "public"."permission" to "anon";

grant select on table "public"."permission" to "anon";

grant trigger on table "public"."permission" to "anon";

grant truncate on table "public"."permission" to "anon";

grant update on table "public"."permission" to "anon";

grant delete on table "public"."permission" to "authenticated";

grant insert on table "public"."permission" to "authenticated";

grant references on table "public"."permission" to "authenticated";

grant select on table "public"."permission" to "authenticated";

grant trigger on table "public"."permission" to "authenticated";

grant truncate on table "public"."permission" to "authenticated";

grant update on table "public"."permission" to "authenticated";

grant delete on table "public"."permission" to "service_role";

grant insert on table "public"."permission" to "service_role";

grant references on table "public"."permission" to "service_role";

grant select on table "public"."permission" to "service_role";

grant trigger on table "public"."permission" to "service_role";

grant truncate on table "public"."permission" to "service_role";

grant update on table "public"."permission" to "service_role";

grant delete on table "public"."role" to "anon";

grant insert on table "public"."role" to "anon";

grant references on table "public"."role" to "anon";

grant select on table "public"."role" to "anon";

grant trigger on table "public"."role" to "anon";

grant truncate on table "public"."role" to "anon";

grant update on table "public"."role" to "anon";

grant delete on table "public"."role" to "authenticated";

grant insert on table "public"."role" to "authenticated";

grant references on table "public"."role" to "authenticated";

grant select on table "public"."role" to "authenticated";

grant trigger on table "public"."role" to "authenticated";

grant truncate on table "public"."role" to "authenticated";

grant update on table "public"."role" to "authenticated";

grant delete on table "public"."role" to "service_role";

grant insert on table "public"."role" to "service_role";

grant references on table "public"."role" to "service_role";

grant select on table "public"."role" to "service_role";

grant trigger on table "public"."role" to "service_role";

grant truncate on table "public"."role" to "service_role";

grant update on table "public"."role" to "service_role";

grant delete on table "public"."role_permission" to "anon";

grant insert on table "public"."role_permission" to "anon";

grant references on table "public"."role_permission" to "anon";

grant select on table "public"."role_permission" to "anon";

grant trigger on table "public"."role_permission" to "anon";

grant truncate on table "public"."role_permission" to "anon";

grant update on table "public"."role_permission" to "anon";

grant delete on table "public"."role_permission" to "authenticated";

grant insert on table "public"."role_permission" to "authenticated";

grant references on table "public"."role_permission" to "authenticated";

grant select on table "public"."role_permission" to "authenticated";

grant trigger on table "public"."role_permission" to "authenticated";

grant truncate on table "public"."role_permission" to "authenticated";

grant update on table "public"."role_permission" to "authenticated";

grant delete on table "public"."role_permission" to "service_role";

grant insert on table "public"."role_permission" to "service_role";

grant references on table "public"."role_permission" to "service_role";

grant select on table "public"."role_permission" to "service_role";

grant trigger on table "public"."role_permission" to "service_role";

grant truncate on table "public"."role_permission" to "service_role";

grant update on table "public"."role_permission" to "service_role";

grant delete on table "public"."test_table_to_test_for_api" to "anon";

grant insert on table "public"."test_table_to_test_for_api" to "anon";

grant references on table "public"."test_table_to_test_for_api" to "anon";

grant select on table "public"."test_table_to_test_for_api" to "anon";

grant trigger on table "public"."test_table_to_test_for_api" to "anon";

grant truncate on table "public"."test_table_to_test_for_api" to "anon";

grant update on table "public"."test_table_to_test_for_api" to "anon";

grant delete on table "public"."test_table_to_test_for_api" to "authenticated";

grant insert on table "public"."test_table_to_test_for_api" to "authenticated";

grant references on table "public"."test_table_to_test_for_api" to "authenticated";

grant select on table "public"."test_table_to_test_for_api" to "authenticated";

grant trigger on table "public"."test_table_to_test_for_api" to "authenticated";

grant truncate on table "public"."test_table_to_test_for_api" to "authenticated";

grant update on table "public"."test_table_to_test_for_api" to "authenticated";

grant delete on table "public"."test_table_to_test_for_api" to "service_role";

grant insert on table "public"."test_table_to_test_for_api" to "service_role";

grant references on table "public"."test_table_to_test_for_api" to "service_role";

grant select on table "public"."test_table_to_test_for_api" to "service_role";

grant trigger on table "public"."test_table_to_test_for_api" to "service_role";

grant truncate on table "public"."test_table_to_test_for_api" to "service_role";

grant update on table "public"."test_table_to_test_for_api" to "service_role";

grant delete on table "public"."user" to "anon";

grant insert on table "public"."user" to "anon";

grant references on table "public"."user" to "anon";

grant select on table "public"."user" to "anon";

grant trigger on table "public"."user" to "anon";

grant truncate on table "public"."user" to "anon";

grant update on table "public"."user" to "anon";

grant delete on table "public"."user" to "authenticated";

grant insert on table "public"."user" to "authenticated";

grant references on table "public"."user" to "authenticated";

grant select on table "public"."user" to "authenticated";

grant trigger on table "public"."user" to "authenticated";

grant truncate on table "public"."user" to "authenticated";

grant update on table "public"."user" to "authenticated";

grant delete on table "public"."user" to "service_role";

grant insert on table "public"."user" to "service_role";

grant references on table "public"."user" to "service_role";

grant select on table "public"."user" to "service_role";

grant trigger on table "public"."user" to "service_role";

grant truncate on table "public"."user" to "service_role";

grant update on table "public"."user" to "service_role";

grant delete on table "public"."user_role" to "anon";

grant insert on table "public"."user_role" to "anon";

grant references on table "public"."user_role" to "anon";

grant select on table "public"."user_role" to "anon";

grant trigger on table "public"."user_role" to "anon";

grant truncate on table "public"."user_role" to "anon";

grant update on table "public"."user_role" to "anon";

grant delete on table "public"."user_role" to "authenticated";

grant insert on table "public"."user_role" to "authenticated";

grant references on table "public"."user_role" to "authenticated";

grant select on table "public"."user_role" to "authenticated";

grant trigger on table "public"."user_role" to "authenticated";

grant truncate on table "public"."user_role" to "authenticated";

grant update on table "public"."user_role" to "authenticated";

grant delete on table "public"."user_role" to "service_role";

grant insert on table "public"."user_role" to "service_role";

grant references on table "public"."user_role" to "service_role";

grant select on table "public"."user_role" to "service_role";

grant trigger on table "public"."user_role" to "service_role";

grant truncate on table "public"."user_role" to "service_role";

grant update on table "public"."user_role" to "service_role";

CREATE TRIGGER update_group_meeting_updated_at BEFORE UPDATE ON public.group_meeting FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_group_meeting_record_updated_at BEFORE UPDATE ON public.group_meeting_record FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


